version: "3"
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     DATABASE_URL: postgresql://postgres:123@db:5432/postgres
  #     JWT_SECRET: mysecret
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - anodos-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - anodos-network
  #   environment:
  #     AUTH_SECRET: mysecret
  #     NEXTAUTH_URL: http://localhost:3000
  #     AUTH_TRUST_HOST: http://localhost:3000
  #     BACKEND_URL: http://localhost:4000

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=123 pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anodos-network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  anodos-network:
